-- ============================================================
--  OBJECT CATALOG  (auto-generated, 444 objects)
--  Shown in the NUI placement menu: pictured, categorised, searchable.
--  `thumb` -> html/img/catalog/<model>.png  (drop image packs named by
--   spawn model name and they appear automatically; missing -> placeholder).
--  `light = true` marks an object you can toggle on/off after placing.
-- ============================================================

Config.CatalogCategories = {
    { id = 'barrier', label = 'Duvar / Çit / Bariyer' },
    { id = 'floor', label = 'Zemin / Platform / Tavan' },
    { id = 'table', label = 'Masa' },
    { id = 'seating', label = 'Sandalye / Koltuk / Oturma' },
    { id = 'decor', label = 'Dekor' },
    { id = 'light', label = 'Aydınlatma' },
    { id = 'bar', label = 'Bar / Kafe / Restoran' },
    { id = 'kitchen', label = 'Mutfak' },
    { id = 'electronics', label = 'Elektronik / Müzik / Oyun' },
    { id = 'home', label = 'Ev / Yatak Odası / Banyo' },
    { id = 'office', label = 'Ofis / İş Yeri' },
    { id = 'gym', label = 'Fight Club / Spor' },
    { id = 'warehouse', label = 'Depo / Industrial / Tamirhane' },
    { id = 'outdoor', label = 'Dış Mekan / Sokak / Kulüp' },
}

Config.Catalog = {

    -- ---------------- Duvar / Çit / Bariyer ----------------
    { name = 'Barrier Wall 01', model = 'prop_barrier_work01a', cat = 'barrier', thumb = 'prop_barrier_work01a.png' },
    { name = 'Barrier Wall 02', model = 'prop_barrier_work02a', cat = 'barrier', thumb = 'prop_barrier_work02a.png' },
    { name = 'Barrier Wall 03', model = 'prop_barrier_work04a', cat = 'barrier', thumb = 'prop_barrier_work04a.png' },
    { name = 'Barrier Wall 04', model = 'prop_barrier_work05', cat = 'barrier', thumb = 'prop_barrier_work05.png' },
    { name = 'Barrier Wall 05', model = 'prop_barrier_work06a', cat = 'barrier', thumb = 'prop_barrier_work06a.png' },
    { name = 'Fence Wood 01', model = 'prop_fncwood_01a', cat = 'barrier', thumb = 'prop_fncwood_01a.png' },
    { name = 'Fence Wood 02', model = 'prop_fncwood_02a', cat = 'barrier', thumb = 'prop_fncwood_02a.png' },
    { name = 'Fence Wood 03', model = 'prop_fncwood_03a', cat = 'barrier', thumb = 'prop_fncwood_03a.png' },
    { name = 'Fence Wood 04', model = 'prop_fncwood_06a', cat = 'barrier', thumb = 'prop_fncwood_06a.png' },
    { name = 'Fence Wood 05', model = 'prop_fncwood_07a', cat = 'barrier', thumb = 'prop_fncwood_07a.png' },
    { name = 'Fence Wood 06', model = 'prop_fncwood_08a', cat = 'barrier', thumb = 'prop_fncwood_08a.png' },
    { name = 'Fence Wood 07', model = 'prop_fncwood_09a', cat = 'barrier', thumb = 'prop_fncwood_09a.png' },
    { name = 'Fence Wood 08', model = 'prop_fncwood_11a', cat = 'barrier', thumb = 'prop_fncwood_11a.png' },
    { name = 'Fence Wood 09', model = 'prop_fncwood_12a', cat = 'barrier', thumb = 'prop_fncwood_12a.png' },
    { name = 'Fence Wood 10', model = 'prop_fncwood_13a', cat = 'barrier', thumb = 'prop_fncwood_13a.png' },
    { name = 'Fence Wood 11', model = 'prop_fncwood_14a', cat = 'barrier', thumb = 'prop_fncwood_14a.png' },
    { name = 'Fence Wood 12', model = 'prop_fncwood_15a', cat = 'barrier', thumb = 'prop_fncwood_15a.png' },
    { name = 'Fence Wood 13', model = 'prop_fncwood_16a', cat = 'barrier', thumb = 'prop_fncwood_16a.png' },
    { name = 'Fence Wood 14', model = 'prop_fncwood_16c', cat = 'barrier', thumb = 'prop_fncwood_16c.png' },
    { name = 'Fence Wood 15', model = 'prop_fncwood_16d', cat = 'barrier', thumb = 'prop_fncwood_16d.png' },
    { name = 'Fence Wood 16', model = 'prop_fncwood_16e', cat = 'barrier', thumb = 'prop_fncwood_16e.png' },
    { name = 'Fence Iron 01', model = 'prop_fnclink_01a', cat = 'barrier', thumb = 'prop_fnclink_01a.png' },
    { name = 'Fence Iron 02', model = 'prop_fnclink_02a', cat = 'barrier', thumb = 'prop_fnclink_02a.png' },
    { name = 'Fence Iron 03', model = 'prop_fnclink_03a', cat = 'barrier', thumb = 'prop_fnclink_03a.png' },
    { name = 'Fence Iron 04', model = 'prop_fnclink_04a', cat = 'barrier', thumb = 'prop_fnclink_04a.png' },
    { name = 'Fence Iron 05', model = 'prop_fnclink_05crnr1', cat = 'barrier', thumb = 'prop_fnclink_05crnr1.png' },
    { name = 'Fence Iron 06', model = 'prop_fnclink_05crnr2', cat = 'barrier', thumb = 'prop_fnclink_05crnr2.png' },
    { name = 'Fence Iron 07', model = 'prop_fnclink_05h', cat = 'barrier', thumb = 'prop_fnclink_05h.png' },
    { name = 'Fence Iron 08', model = 'prop_fnclink_05i', cat = 'barrier', thumb = 'prop_fnclink_05i.png' },
    { name = 'Fence Iron 09', model = 'prop_fnclink_06gate2', cat = 'barrier', thumb = 'prop_fnclink_06gate2.png' },
    { name = 'Fence Iron 10', model = 'prop_fnclink_07gate1', cat = 'barrier', thumb = 'prop_fnclink_07gate1.png' },
    { name = 'Fence Iron 11', model = 'prop_fnclink_09gate1', cat = 'barrier', thumb = 'prop_fnclink_09gate1.png' },
    { name = 'Wall Brick 01', model = 'prop_wallbrick_01', cat = 'barrier', thumb = 'prop_wallbrick_01.png' },
    { name = 'Wall Light Panel', model = 'prop_ind_walllight02', cat = 'barrier', thumb = 'prop_ind_walllight02.png' },
    { name = 'Metal Sheeting 01', model = 'prop_sheeting01', cat = 'barrier', thumb = 'prop_sheeting01.png' },
    { name = 'Metal Sheeting 02', model = 'prop_sheeting02', cat = 'barrier', thumb = 'prop_sheeting02.png' },
    { name = 'Metal Sheeting 03', model = 'prop_sheeting03', cat = 'barrier', thumb = 'prop_sheeting03.png' },
    { name = 'Scaffolding 01', model = 'prop_scaffolding_01', cat = 'barrier', thumb = 'prop_scaffolding_01.png' },
    { name = 'Scaffolding 02', model = 'prop_scaffolding_02a', cat = 'barrier', thumb = 'prop_scaffolding_02a.png' },
    { name = 'Scaffolding 03', model = 'prop_scaffolding_03c', cat = 'barrier', thumb = 'prop_scaffolding_03c.png' },
    { name = 'Military Gate', model = 'prop_gate_military_01', cat = 'barrier', thumb = 'prop_gate_military_01.png' },
    { name = 'Gate Prison 01', model = 'prop_gate_prison_01', cat = 'barrier', thumb = 'prop_gate_prison_01.png' },
    { name = 'Gate Frame 01', model = 'prop_gate_frame_01', cat = 'barrier', thumb = 'prop_gate_frame_01.png' },
    { name = 'Railing 01', model = 'prop_railing_paddock', cat = 'barrier', thumb = 'prop_railing_paddock.png' },
    { name = 'Railing 02', model = 'prop_mb_craig_02a', cat = 'barrier', thumb = 'prop_mb_craig_02a.png' },
    { name = 'Concrete Barrier 01', model = 'prop_mp_barrier_01', cat = 'barrier', thumb = 'prop_mp_barrier_01.png' },
    { name = 'Concrete Barrier 02', model = 'prop_mp_barrier_02b', cat = 'barrier', thumb = 'prop_mp_barrier_02b.png' },
    { name = 'Road Barrier 01', model = 'prop_mp_arrow_barrier_01', cat = 'barrier', thumb = 'prop_mp_arrow_barrier_01.png' },
    { name = 'Road Barrier 02', model = 'prop_barier_conc_01a', cat = 'barrier', thumb = 'prop_barier_conc_01a.png' },

    -- ---------------- Zemin / Platform / Tavan ----------------
    { name = 'Platform 01', model = 'prop_ld_dstplane', cat = 'floor', thumb = 'prop_ld_dstplane.png' },
    { name = 'Platform 02', model = 'prop_ld_dstplane_02', cat = 'floor', thumb = 'prop_ld_dstplane_02.png' },
    { name = 'Platform 03', model = 'prop_ld_toilet_01', cat = 'floor', thumb = 'prop_ld_toilet_01.png' },
    { name = 'Stage Floor 01', model = 'prop_stage_floor_01', cat = 'floor', thumb = 'prop_stage_floor_01.png' },
    { name = 'Stage Floor 02', model = 'prop_stage_floor_02', cat = 'floor', thumb = 'prop_stage_floor_02.png' },
    { name = 'Stage Floor 03', model = 'prop_stage_floor_03', cat = 'floor', thumb = 'prop_stage_floor_03.png' },
    { name = 'Stage Floor 04', model = 'prop_stage_floor_04', cat = 'floor', thumb = 'prop_stage_floor_04.png' },
    { name = 'Floor Diamond 01', model = 'prop_floor_diamond_01', cat = 'floor', thumb = 'prop_floor_diamond_01.png' },
    { name = 'Floor Diamond 02', model = 'prop_floor_diamond_02', cat = 'floor', thumb = 'prop_floor_diamond_02.png' },
    { name = 'Wood Ramp 01', model = 'prop_woodpile_01a', cat = 'floor', thumb = 'prop_woodpile_01a.png' },
    { name = 'Wood Ramp 02', model = 'prop_woodpile_02a', cat = 'floor', thumb = 'prop_woodpile_02a.png' },
    { name = 'Dock Ramp 01', model = 'prop_dock_rtg_ld', cat = 'floor', thumb = 'prop_dock_rtg_ld.png' },
    { name = 'Dock Ramp 02', model = 'prop_dock_rtg_01', cat = 'floor', thumb = 'prop_dock_rtg_01.png' },
    { name = 'Concrete Base 01', model = 'prop_conslift_base', cat = 'floor', thumb = 'prop_conslift_base.png' },
    { name = 'Concrete Base 02', model = 'prop_cons_ply01', cat = 'floor', thumb = 'prop_cons_ply01.png' },
    { name = 'Concrete Base 03', model = 'prop_cons_ply02', cat = 'floor', thumb = 'prop_cons_ply02.png' },
    { name = 'Container Floor 01', model = 'prop_container_01a', cat = 'floor', thumb = 'prop_container_01a.png' },
    { name = 'Container Floor 02', model = 'prop_container_03b', cat = 'floor', thumb = 'prop_container_03b.png' },
    { name = 'Container Floor 03', model = 'prop_container_05a', cat = 'floor', thumb = 'prop_container_05a.png' },
    { name = 'Pallet Base 01', model = 'prop_pallet_01a', cat = 'floor', thumb = 'prop_pallet_01a.png' },
    { name = 'Pallet Base 02', model = 'prop_pallet_02a', cat = 'floor', thumb = 'prop_pallet_02a.png' },
    { name = 'Pallet Base 03', model = 'prop_pallet_03a', cat = 'floor', thumb = 'prop_pallet_03a.png' },
    { name = 'Pallet Base 04', model = 'prop_pallet_04a', cat = 'floor', thumb = 'prop_pallet_04a.png' },
    { name = 'Roof Bit 01', model = 'prop_roofpipe_01', cat = 'floor', thumb = 'prop_roofpipe_01.png' },
    { name = 'Roof Bit 02', model = 'prop_roofpipe_02', cat = 'floor', thumb = 'prop_roofpipe_02.png' },
    { name = 'Metal Frame 01', model = 'prop_byard_float_01', cat = 'floor', thumb = 'prop_byard_float_01.png' },
    { name = 'Metal Frame 02', model = 'prop_byard_float_02', cat = 'floor', thumb = 'prop_byard_float_02.png' },
    { name = 'Metal Frame 03', model = 'prop_byard_float_03', cat = 'floor', thumb = 'prop_byard_float_03.png' },
    { name = 'Boat Platform', model = 'prop_byard_rampold_cr', cat = 'floor', thumb = 'prop_byard_rampold_cr.png' },
    { name = 'Wood Board 01', model = 'prop_rub_planks_01', cat = 'floor', thumb = 'prop_rub_planks_01.png' },
    { name = 'Wood Board 02', model = 'prop_rub_planks_02', cat = 'floor', thumb = 'prop_rub_planks_02.png' },
    { name = 'Wood Board 03', model = 'prop_rub_planks_03', cat = 'floor', thumb = 'prop_rub_planks_03.png' },
    { name = 'Wood Board 04', model = 'prop_rub_planks_04', cat = 'floor', thumb = 'prop_rub_planks_04.png' },
    { name = 'Mat 01', model = 'prop_yoga_mat_01', cat = 'floor', thumb = 'prop_yoga_mat_01.png' },
    { name = 'Mat 02', model = 'prop_yoga_mat_02', cat = 'floor', thumb = 'prop_yoga_mat_02.png' },
    { name = 'Mat 03', model = 'prop_yoga_mat_03', cat = 'floor', thumb = 'prop_yoga_mat_03.png' },

    -- ---------------- Masa ----------------
    { name = 'Table 01', model = 'prop_table_01', cat = 'table', thumb = 'prop_table_01.png' },
    { name = 'Table 02', model = 'prop_table_02', cat = 'table', thumb = 'prop_table_02.png' },
    { name = 'Table 03', model = 'prop_table_03', cat = 'table', thumb = 'prop_table_03.png' },
    { name = 'Table 04', model = 'prop_table_04', cat = 'table', thumb = 'prop_table_04.png' },
    { name = 'Desk 01', model = 'prop_office_desk_01', cat = 'table', thumb = 'prop_office_desk_01.png' },
    { name = 'Desk 02', model = 'prop_office_desk_02', cat = 'table', thumb = 'prop_office_desk_02.png' },
    { name = 'Dining Table 01', model = 'prop_dining_table_01', cat = 'table', thumb = 'prop_dining_table_01.png' },
    { name = 'Dining Table 02', model = 'prop_dining_table_02', cat = 'table', thumb = 'prop_dining_table_02.png' },
    { name = 'Farm Table', model = 'prop_rub_table_01', cat = 'table', thumb = 'prop_rub_table_01.png' },
    { name = 'Bar Table 01', model = 'prop_bar_table_01', cat = 'table', thumb = 'prop_bar_table_01.png' },
    { name = 'Coffee Table 01', model = 'prop_t_coffe_table', cat = 'table', thumb = 'prop_t_coffe_table.png' },
    { name = 'Coffee Table 02', model = 'prop_t_coffe_table_02', cat = 'table', thumb = 'prop_t_coffe_table_02.png' },
    { name = 'Poker Table', model = 'prop_poker_table_01', cat = 'table', thumb = 'prop_poker_table_01.png' },
    { name = 'Workbench 01', model = 'prop_tool_bench02', cat = 'table', thumb = 'prop_tool_bench02.png' },
    { name = 'Workbench 02', model = 'prop_worklight_03b', cat = 'table', thumb = 'prop_worklight_03b.png' },
    { name = 'Side Table', model = 'v_res_tre_sideboard', cat = 'table', thumb = 'v_res_tre_sideboard.png' },

    -- ---------------- Sandalye / Koltuk / Oturma ----------------
    { name = 'Chair 01', model = 'prop_chair_01a', cat = 'seating', thumb = 'prop_chair_01a.png' },
    { name = 'Chair 02', model = 'prop_chair_03', cat = 'seating', thumb = 'prop_chair_03.png' },
    { name = 'Chair 03', model = 'prop_chair_04a', cat = 'seating', thumb = 'prop_chair_04a.png' },
    { name = 'Chair 04', model = 'prop_chair_05', cat = 'seating', thumb = 'prop_chair_05.png' },
    { name = 'Chair 05', model = 'prop_chair_06', cat = 'seating', thumb = 'prop_chair_06.png' },
    { name = 'Chair 06', model = 'prop_chair_07', cat = 'seating', thumb = 'prop_chair_07.png' },
    { name = 'Chair 07', model = 'prop_chair_08', cat = 'seating', thumb = 'prop_chair_08.png' },
    { name = 'Chair 08', model = 'prop_chair_pile_01', cat = 'seating', thumb = 'prop_chair_pile_01.png' },
    { name = 'Plastic Chair 01', model = 'prop_chair_plastic', cat = 'seating', thumb = 'prop_chair_plastic.png' },
    { name = 'Plastic Chair 02', model = 'prop_chair_bin_01', cat = 'seating', thumb = 'prop_chair_bin_01.png' },
    { name = 'Office Chair 01', model = 'prop_off_chair_01', cat = 'seating', thumb = 'prop_off_chair_01.png' },
    { name = 'Office Chair 02', model = 'prop_off_chair_03', cat = 'seating', thumb = 'prop_off_chair_03.png' },
    { name = 'Office Chair 03', model = 'prop_off_chair_04', cat = 'seating', thumb = 'prop_off_chair_04.png' },
    { name = 'Stool 01', model = 'prop_bar_stool_01', cat = 'seating', thumb = 'prop_bar_stool_01.png' },
    { name = 'Stool 02', model = 'prop_bar_stool_02', cat = 'seating', thumb = 'prop_bar_stool_02.png' },
    { name = 'Bench 01', model = 'prop_bench_01a', cat = 'seating', thumb = 'prop_bench_01a.png' },
    { name = 'Bench 02', model = 'prop_bench_01b', cat = 'seating', thumb = 'prop_bench_01b.png' },
    { name = 'Bench 03', model = 'prop_bench_01c', cat = 'seating', thumb = 'prop_bench_01c.png' },
    { name = 'Bench 04', model = 'prop_bench_02', cat = 'seating', thumb = 'prop_bench_02.png' },
    { name = 'Bench 05', model = 'prop_bench_03', cat = 'seating', thumb = 'prop_bench_03.png' },
    { name = 'Bench 06', model = 'prop_bench_04', cat = 'seating', thumb = 'prop_bench_04.png' },
    { name = 'Couch 01', model = 'prop_couch_01', cat = 'seating', thumb = 'prop_couch_01.png' },
    { name = 'Couch 02', model = 'prop_couch_02', cat = 'seating', thumb = 'prop_couch_02.png' },
    { name = 'Couch 03', model = 'prop_couch_03', cat = 'seating', thumb = 'prop_couch_03.png' },
    { name = 'Couch 04', model = 'prop_couch_04', cat = 'seating', thumb = 'prop_couch_04.png' },
    { name = 'Couch Large 01', model = 'prop_couch_lg_02', cat = 'seating', thumb = 'prop_couch_lg_02.png' },
    { name = 'Armchair 01', model = 'prop_armchair_01', cat = 'seating', thumb = 'prop_armchair_01.png' },
    { name = 'Armchair 02', model = 'prop_cs_folding_chair_01', cat = 'seating', thumb = 'prop_cs_folding_chair_01.png' },
    { name = 'Bean Bag', model = 'prop_bean_bag_01', cat = 'seating', thumb = 'prop_bean_bag_01.png' },
    { name = 'Sun Lounger 01', model = 'prop_ld_farm_chair01', cat = 'seating', thumb = 'prop_ld_farm_chair01.png' },

    -- ---------------- Dekor ----------------
    { name = 'Plant 01', model = 'prop_plant_int_01a', cat = 'decor', thumb = 'prop_plant_int_01a.png' },
    { name = 'Plant 02', model = 'prop_plant_int_01b', cat = 'decor', thumb = 'prop_plant_int_01b.png' },
    { name = 'Plant 03', model = 'prop_plant_int_02a', cat = 'decor', thumb = 'prop_plant_int_02a.png' },
    { name = 'Plant 04', model = 'prop_plant_int_02b', cat = 'decor', thumb = 'prop_plant_int_02b.png' },
    { name = 'Plant 05', model = 'prop_plant_int_03a', cat = 'decor', thumb = 'prop_plant_int_03a.png' },
    { name = 'Plant 06', model = 'prop_plant_int_03b', cat = 'decor', thumb = 'prop_plant_int_03b.png' },
    { name = 'Plant 07', model = 'prop_plant_int_04a', cat = 'decor', thumb = 'prop_plant_int_04a.png' },
    { name = 'Plant 08', model = 'prop_plant_int_04b', cat = 'decor', thumb = 'prop_plant_int_04b.png' },
    { name = 'Plant 09', model = 'prop_pot_plant_01a', cat = 'decor', thumb = 'prop_pot_plant_01a.png' },
    { name = 'Plant 10', model = 'prop_pot_plant_01b', cat = 'decor', thumb = 'prop_pot_plant_01b.png' },
    { name = 'Plant 11', model = 'prop_pot_plant_01c', cat = 'decor', thumb = 'prop_pot_plant_01c.png' },
    { name = 'Plant 12', model = 'prop_pot_plant_01d', cat = 'decor', thumb = 'prop_pot_plant_01d.png' },
    { name = 'Mirror 01', model = 'prop_mirror_01', cat = 'decor', thumb = 'prop_mirror_01.png' },
    { name = 'Mirror 02', model = 'prop_mirror_wal_02', cat = 'decor', thumb = 'prop_mirror_wal_02.png' },
    { name = 'Clock', model = 'prop_wall_clock', cat = 'decor', thumb = 'prop_wall_clock.png' },
    { name = 'Painting 01', model = 'prop_painting_01a', cat = 'decor', thumb = 'prop_painting_01a.png' },
    { name = 'Painting 02', model = 'prop_painting_01b', cat = 'decor', thumb = 'prop_painting_01b.png' },
    { name = 'Painting 03', model = 'prop_painting_02a', cat = 'decor', thumb = 'prop_painting_02a.png' },
    { name = 'Painting 04', model = 'prop_painting_03', cat = 'decor', thumb = 'prop_painting_03.png' },
    { name = 'Painting 05', model = 'prop_painting_04', cat = 'decor', thumb = 'prop_painting_04.png' },
    { name = 'Statue 01', model = 'prop_statue_horse', cat = 'decor', thumb = 'prop_statue_horse.png' },
    { name = 'Statue 02', model = 'prop_statue_bird_01', cat = 'decor', thumb = 'prop_statue_bird_01.png' },
    { name = 'Statue 03', model = 'prop_statue_horse_01', cat = 'decor', thumb = 'prop_statue_horse_01.png' },
    { name = 'Rug 01', model = 'prop_rug_01', cat = 'decor', thumb = 'prop_rug_01.png' },
    { name = 'Rug 02', model = 'prop_rug_01b', cat = 'decor', thumb = 'prop_rug_01b.png' },
    { name = 'Rug 03', model = 'prop_rug_01c', cat = 'decor', thumb = 'prop_rug_01c.png' },
    { name = 'Rug 04', model = 'prop_rug_10', cat = 'decor', thumb = 'prop_rug_10.png' },
    { name = 'Rug 05', model = 'prop_rug_11', cat = 'decor', thumb = 'prop_rug_11.png' },
    { name = 'Candles 01', model = 'prop_cs_candle_01', cat = 'decor', thumb = 'prop_cs_candle_01.png' },
    { name = 'Candles 02', model = 'prop_cs_candle_02', cat = 'decor', thumb = 'prop_cs_candle_02.png' },
    { name = 'Vase 01', model = 'v_res_m_vasefresh', cat = 'decor', thumb = 'v_res_m_vasefresh.png' },
    { name = 'Vase 02', model = 'v_res_desktidy', cat = 'decor', thumb = 'v_res_desktidy.png' },
    { name = 'Books 01', model = 'prop_books_01', cat = 'decor', thumb = 'prop_books_01.png' },
    { name = 'Books 02', model = 'prop_books_02', cat = 'decor', thumb = 'prop_books_02.png' },
    { name = 'Books 03', model = 'prop_books_03', cat = 'decor', thumb = 'prop_books_03.png' },
    { name = 'Books 04', model = 'prop_books_04', cat = 'decor', thumb = 'prop_books_04.png' },
    { name = 'Books 05', model = 'prop_books_05', cat = 'decor', thumb = 'prop_books_05.png' },
    { name = 'Books 06', model = 'prop_books_06', cat = 'decor', thumb = 'prop_books_06.png' },
    { name = 'Magazine Rack', model = 'prop_magenta_door', cat = 'decor', thumb = 'prop_magenta_door.png' },
    { name = 'Bin 01', model = 'prop_bin_01a', cat = 'decor', thumb = 'prop_bin_01a.png' },
    { name = 'Bin 02', model = 'prop_bin_02a', cat = 'decor', thumb = 'prop_bin_02a.png' },
    { name = 'Bin 03', model = 'prop_bin_05a', cat = 'decor', thumb = 'prop_bin_05a.png' },
    { name = 'Ashtray', model = 'prop_cs_ashtray', cat = 'decor', thumb = 'prop_cs_ashtray.png' },
    { name = 'Cigarette Tray', model = 'prop_cs_ciggy_01', cat = 'decor', thumb = 'prop_cs_ciggy_01.png' },
    { name = 'Umbrella Stand', model = 'prop_parasol_01', cat = 'decor', thumb = 'prop_parasol_01.png' },

    -- ---------------- Aydınlatma ----------------
    { name = 'Floor Lamp 01', model = 'prop_floorlamp_01', cat = 'light', thumb = 'prop_floorlamp_01.png', light = true },
    { name = 'Floor Lamp 02', model = 'prop_floorlamp_02', cat = 'light', thumb = 'prop_floorlamp_02.png', light = true },
    { name = 'Floor Lamp 03', model = 'v_res_fh_floorlamp', cat = 'light', thumb = 'v_res_fh_floorlamp.png', light = true },
    { name = 'Desk Lamp 01', model = 'prop_table_lamp_01', cat = 'light', thumb = 'prop_table_lamp_01.png', light = true },
    { name = 'Desk Lamp 02', model = 'prop_table_lamp_02', cat = 'light', thumb = 'prop_table_lamp_02.png', light = true },
    { name = 'Desk Lamp 03', model = 'v_res_d_lampa', cat = 'light', thumb = 'v_res_d_lampa.png', light = true },
    { name = 'Ceiling Light 01', model = 'prop_ceiling_light_01', cat = 'light', thumb = 'prop_ceiling_light_01.png', light = true },
    { name = 'Ceiling Light 02', model = 'prop_ceiling_light_02', cat = 'light', thumb = 'prop_ceiling_light_02.png', light = true },
    { name = 'Ceiling Light 03', model = 'prop_ceiling_light_09', cat = 'light', thumb = 'prop_ceiling_light_09.png', light = true },
    { name = 'Wall Light 01', model = 'prop_wall_light_02a', cat = 'light', thumb = 'prop_wall_light_02a.png', light = true },
    { name = 'Wall Light 02', model = 'prop_wall_light_03a', cat = 'light', thumb = 'prop_wall_light_03a.png', light = true },
    { name = 'Wall Light 03', model = 'prop_wall_light_04a', cat = 'light', thumb = 'prop_wall_light_04a.png', light = true },
    { name = 'Industrial Light 01', model = 'prop_ind_light_02a', cat = 'light', thumb = 'prop_ind_light_02a.png', light = true },
    { name = 'Industrial Light 02', model = 'prop_worklight_01a', cat = 'light', thumb = 'prop_worklight_01a.png', light = true },
    { name = 'Industrial Light 03', model = 'prop_worklight_03a', cat = 'light', thumb = 'prop_worklight_03a.png', light = true },
    { name = 'Industrial Light 04', model = 'prop_worklight_04a', cat = 'light', thumb = 'prop_worklight_04a.png', light = true },
    { name = 'Industrial Light 05', model = 'prop_worklight_04b', cat = 'light', thumb = 'prop_worklight_04b.png', light = true },
    { name = 'Neon Tube 01', model = 'prop_neon_tube_01', cat = 'light', thumb = 'prop_neon_tube_01.png', light = true },
    { name = 'Neon Tube 02', model = 'prop_neon_tube_02', cat = 'light', thumb = 'prop_neon_tube_02.png', light = true },
    { name = 'Neon Tube 03', model = 'prop_neon_tube_03', cat = 'light', thumb = 'prop_neon_tube_03.png', light = true },
    { name = 'Lantern 01', model = 'prop_oldlight_01c', cat = 'light', thumb = 'prop_oldlight_01c.png', light = true },
    { name = 'Lantern 02', model = 'prop_oldlight_01b', cat = 'light', thumb = 'prop_oldlight_01b.png', light = true },
    { name = 'Street Light Small', model = 'prop_streetlight_01', cat = 'light', thumb = 'prop_streetlight_01.png', light = true },
    { name = 'Street Light Medium', model = 'prop_streetlight_03', cat = 'light', thumb = 'prop_streetlight_03.png', light = true },
    { name = 'Street Light Big', model = 'prop_streetlight_11b', cat = 'light', thumb = 'prop_streetlight_11b.png', light = true },

    -- ---------------- Bar / Kafe / Restoran ----------------
    { name = 'Bar Counter 01', model = 'prop_bar_counter_01', cat = 'bar', thumb = 'prop_bar_counter_01.png' },
    { name = 'Bar Counter 02', model = 'prop_bar_counter_02', cat = 'bar', thumb = 'prop_bar_counter_02.png' },
    { name = 'Bar Counter 03', model = 'prop_bar_counter_07', cat = 'bar', thumb = 'prop_bar_counter_07.png' },
    { name = 'Bar Beer Tap 01', model = 'prop_beer_tap_01', cat = 'bar', thumb = 'prop_beer_tap_01.png' },
    { name = 'Bar Beer Tap 02', model = 'prop_beer_tap_02', cat = 'bar', thumb = 'prop_beer_tap_02.png' },
    { name = 'Bar Pump 01', model = 'prop_bar_pump_01', cat = 'bar', thumb = 'prop_bar_pump_01.png' },
    { name = 'Bar Pump 02', model = 'prop_bar_pump_06', cat = 'bar', thumb = 'prop_bar_pump_06.png' },
    { name = 'Bar Pump 03', model = 'prop_bar_pump_07', cat = 'bar', thumb = 'prop_bar_pump_07.png' },
    { name = 'Bar Fridge 01', model = 'prop_bar_fridge_01', cat = 'bar', thumb = 'prop_bar_fridge_01.png' },
    { name = 'Bar Fridge 02', model = 'prop_bar_fridge_02', cat = 'bar', thumb = 'prop_bar_fridge_02.png' },
    { name = 'Bottle Shelf 01', model = 'prop_bar_beans', cat = 'bar', thumb = 'prop_bar_beans.png' },
    { name = 'Bottle Shelf 02', model = 'prop_bar_measr_01', cat = 'bar', thumb = 'prop_bar_measr_01.png' },
    { name = 'Bottle Shelf 03', model = 'prop_bar_measr_02', cat = 'bar', thumb = 'prop_bar_measr_02.png' },
    { name = 'Bottle Shelf 04', model = 'prop_bar_measr_03', cat = 'bar', thumb = 'prop_bar_measr_03.png' },
    { name = 'Cash Register 01', model = 'prop_till_01', cat = 'bar', thumb = 'prop_till_01.png' },
    { name = 'Cash Register 02', model = 'prop_till_02', cat = 'bar', thumb = 'prop_till_02.png' },
    { name = 'Cash Register 03', model = 'prop_till_03', cat = 'bar', thumb = 'prop_till_03.png' },
    { name = 'Coffee Machine 01', model = 'prop_coffee_mac_01', cat = 'bar', thumb = 'prop_coffee_mac_01.png' },
    { name = 'Coffee Machine 02', model = 'prop_coffee_mac_02', cat = 'bar', thumb = 'prop_coffee_mac_02.png' },
    { name = 'Coffee Machine 03', model = 'p_ld_coffee_vend_01', cat = 'bar', thumb = 'p_ld_coffee_vend_01.png' },
    { name = 'Cup Stack', model = 'prop_cups_01', cat = 'bar', thumb = 'prop_cups_01.png' },
    { name = 'Menu Board 01', model = 'prop_menu_board_01', cat = 'bar', thumb = 'prop_menu_board_01.png' },
    { name = 'Menu Board 02', model = 'prop_menu_board_02', cat = 'bar', thumb = 'prop_menu_board_02.png' },
    { name = 'Menu Board 03', model = 'prop_menu_board_03', cat = 'bar', thumb = 'prop_menu_board_03.png' },
    { name = 'Neon Sign 01', model = 'prop_neon_sign_01', cat = 'bar', thumb = 'prop_neon_sign_01.png' },
    { name = 'Neon Sign 02', model = 'prop_neon_sign_02', cat = 'bar', thumb = 'prop_neon_sign_02.png' },
    { name = 'Neon Sign 03', model = 'prop_neon_sign_03', cat = 'bar', thumb = 'prop_neon_sign_03.png' },
    { name = 'Neon Sign 04', model = 'prop_neon_sign_04', cat = 'bar', thumb = 'prop_neon_sign_04.png' },
    { name = 'Neon Sign 05', model = 'prop_neon_sign_05', cat = 'bar', thumb = 'prop_neon_sign_05.png' },
    { name = 'Drink Machine 01', model = 'prop_vend_soda_01', cat = 'bar', thumb = 'prop_vend_soda_01.png' },
    { name = 'Drink Machine 02', model = 'prop_vend_soda_02', cat = 'bar', thumb = 'prop_vend_soda_02.png' },
    { name = 'Snack Machine 01', model = 'prop_vend_snak_01', cat = 'bar', thumb = 'prop_vend_snak_01.png' },
    { name = 'Snack Machine 02', model = 'prop_vend_snak_01_tu', cat = 'bar', thumb = 'prop_vend_snak_01_tu.png' },
    { name = 'Popcorn Machine', model = 'prop_popcorn_01', cat = 'bar', thumb = 'prop_popcorn_01.png' },
    { name = 'Microwave Cafe', model = 'prop_micro_01', cat = 'bar', thumb = 'prop_micro_01.png' },
    { name = 'Display Fridge', model = 'prop_vend_fridge01', cat = 'bar', thumb = 'prop_vend_fridge01.png' },
    { name = 'Ice Box', model = 'prop_ice_box_01', cat = 'bar', thumb = 'prop_ice_box_01.png' },
    { name = 'Pizza Box', model = 'prop_pizza_box_02', cat = 'bar', thumb = 'prop_pizza_box_02.png' },
    { name = 'Table Tray', model = 'prop_food_tray_01', cat = 'bar', thumb = 'prop_food_tray_01.png' },
    { name = 'Table Tray 02', model = 'prop_food_bs_tray_03', cat = 'bar', thumb = 'prop_food_bs_tray_03.png' },
    { name = 'Food Bag', model = 'prop_food_bs_bag_01', cat = 'bar', thumb = 'prop_food_bs_bag_01.png' },
    { name = 'Napkin Holder', model = 'prop_food_bs_soda_01', cat = 'bar', thumb = 'prop_food_bs_soda_01.png' },
    { name = 'Bottle Rack', model = 'prop_wine_red', cat = 'bar', thumb = 'prop_wine_red.png' },

    -- ---------------- Mutfak ----------------
    { name = 'Fridge 01', model = 'prop_fridge_01', cat = 'kitchen', thumb = 'prop_fridge_01.png' },
    { name = 'Fridge 02', model = 'prop_fridge_03', cat = 'kitchen', thumb = 'prop_fridge_03.png' },
    { name = 'Fridge 03', model = 'prop_fridge_04', cat = 'kitchen', thumb = 'prop_fridge_04.png' },
    { name = 'Fridge 04', model = 'prop_fridge_05', cat = 'kitchen', thumb = 'prop_fridge_05.png' },
    { name = 'Oven 01', model = 'prop_oven_01', cat = 'kitchen', thumb = 'prop_oven_01.png' },
    { name = 'Oven 02', model = 'prop_range_hood_01', cat = 'kitchen', thumb = 'prop_range_hood_01.png' },
    { name = 'Microwave 01', model = 'prop_micro_01', cat = 'kitchen', thumb = 'prop_micro_01.png' },
    { name = 'Microwave 02', model = 'prop_microwave_1', cat = 'kitchen', thumb = 'prop_microwave_1.png' },
    { name = 'Sink 01', model = 'prop_sink_02', cat = 'kitchen', thumb = 'prop_sink_02.png' },
    { name = 'Sink 02', model = 'prop_sink_03', cat = 'kitchen', thumb = 'prop_sink_03.png' },
    { name = 'Counter 01', model = 'prop_kitch_counter_01', cat = 'kitchen', thumb = 'prop_kitch_counter_01.png' },
    { name = 'Counter 02', model = 'prop_kitch_juicer', cat = 'kitchen', thumb = 'prop_kitch_juicer.png' },
    { name = 'Counter 03', model = 'prop_kitch_pot_fry', cat = 'kitchen', thumb = 'prop_kitch_pot_fry.png' },
    { name = 'Counter 04', model = 'prop_kitch_pot_huge', cat = 'kitchen', thumb = 'prop_kitch_pot_huge.png' },
    { name = 'Toaster', model = 'prop_toaster_01', cat = 'kitchen', thumb = 'prop_toaster_01.png' },
    { name = 'Blender', model = 'prop_blender_01', cat = 'kitchen', thumb = 'prop_blender_01.png' },
    { name = 'Cutting Board', model = 'prop_cs_kitchen_cab_l', cat = 'kitchen', thumb = 'prop_cs_kitchen_cab_l.png' },
    { name = 'Knife Block', model = 'v_res_knifeblock', cat = 'kitchen', thumb = 'v_res_knifeblock.png' },
    { name = 'Mug Rack', model = 'prop_mug_01', cat = 'kitchen', thumb = 'prop_mug_01.png' },
    { name = 'Mug Rack 02', model = 'prop_mug_02', cat = 'kitchen', thumb = 'prop_mug_02.png' },
    { name = 'Plate Rack', model = 'prop_plate_01', cat = 'kitchen', thumb = 'prop_plate_01.png' },
    { name = 'Pan', model = 'prop_pot_03', cat = 'kitchen', thumb = 'prop_pot_03.png' },
    { name = 'Pot', model = 'prop_pot_02', cat = 'kitchen', thumb = 'prop_pot_02.png' },
    { name = 'Gas Bottle', model = 'prop_gascyl_01a', cat = 'kitchen', thumb = 'prop_gascyl_01a.png' },
    { name = 'Gas Bottle 02', model = 'prop_gascyl_04a', cat = 'kitchen', thumb = 'prop_gascyl_04a.png' },

    -- ---------------- Elektronik / Müzik / Oyun ----------------
    { name = 'TV Flat 01', model = 'prop_tv_flat_01', cat = 'electronics', thumb = 'prop_tv_flat_01.png' },
    { name = 'TV Flat 02', model = 'prop_tv_flat_02', cat = 'electronics', thumb = 'prop_tv_flat_02.png' },
    { name = 'TV Flat 03', model = 'prop_tv_flat_03', cat = 'electronics', thumb = 'prop_tv_flat_03.png' },
    { name = 'TV Small 01', model = 'prop_tv_03', cat = 'electronics', thumb = 'prop_tv_03.png' },
    { name = 'TV Small 02', model = 'prop_tv_05', cat = 'electronics', thumb = 'prop_tv_05.png' },
    { name = 'TV Small 03', model = 'prop_tv_06', cat = 'electronics', thumb = 'prop_tv_06.png' },
    { name = 'Laptop 01', model = 'prop_laptop_01a', cat = 'electronics', thumb = 'prop_laptop_01a.png' },
    { name = 'Laptop 02', model = 'prop_laptop_lester2', cat = 'electronics', thumb = 'prop_laptop_lester2.png' },
    { name = 'Laptop 03', model = 'p_amb_lap_top_02', cat = 'electronics', thumb = 'p_amb_lap_top_02.png' },
    { name = 'Monitor 01', model = 'prop_monitor_01a', cat = 'electronics', thumb = 'prop_monitor_01a.png' },
    { name = 'Monitor 02', model = 'prop_monitor_01b', cat = 'electronics', thumb = 'prop_monitor_01b.png' },
    { name = 'Monitor 03', model = 'prop_monitor_02', cat = 'electronics', thumb = 'prop_monitor_02.png' },
    { name = 'PC Tower', model = 'prop_pc_01a', cat = 'electronics', thumb = 'prop_pc_01a.png' },
    { name = 'Keyboard', model = 'prop_keyboard_01a', cat = 'electronics', thumb = 'prop_keyboard_01a.png' },
    { name = 'Mouse', model = 'prop_cs_mouse_01', cat = 'electronics', thumb = 'prop_cs_mouse_01.png' },
    { name = 'Printer 01', model = 'prop_printer_01', cat = 'electronics', thumb = 'prop_printer_01.png' },
    { name = 'Printer 02', model = 'prop_printer_02', cat = 'electronics', thumb = 'prop_printer_02.png' },
    { name = 'Speaker 01', model = 'prop_speaker_01', cat = 'electronics', thumb = 'prop_speaker_01.png' },
    { name = 'Speaker 02', model = 'prop_speaker_02', cat = 'electronics', thumb = 'prop_speaker_02.png' },
    { name = 'Speaker 03', model = 'prop_speaker_03', cat = 'electronics', thumb = 'prop_speaker_03.png' },
    { name = 'Speaker 04', model = 'prop_speaker_05', cat = 'electronics', thumb = 'prop_speaker_05.png' },
    { name = 'Boom Box 01', model = 'prop_boombox_01', cat = 'electronics', thumb = 'prop_boombox_01.png' },
    { name = 'Boom Box 02', model = 'prop_cs_cctv', cat = 'electronics', thumb = 'prop_cs_cctv.png' },
    { name = 'DJ Deck 01', model = 'prop_dj_deck_01', cat = 'electronics', thumb = 'prop_dj_deck_01.png' },
    { name = 'DJ Deck 02', model = 'prop_dj_deck_02', cat = 'electronics', thumb = 'prop_dj_deck_02.png' },
    { name = 'Arcade Machine 01', model = 'prop_arcade_01', cat = 'electronics', thumb = 'prop_arcade_01.png' },
    { name = 'Arcade Machine 02', model = 'prop_arcade_02', cat = 'electronics', thumb = 'prop_arcade_02.png' },
    { name = 'Arcade Machine 03', model = 'prop_arcade_03', cat = 'electronics', thumb = 'prop_arcade_03.png' },
    { name = 'Arcade Machine 04', model = 'prop_arcade_04', cat = 'electronics', thumb = 'prop_arcade_04.png' },
    { name = 'Phone 01', model = 'prop_phone_ing', cat = 'electronics', thumb = 'prop_phone_ing.png' },
    { name = 'Phone 02', model = 'prop_phone_cs_frank', cat = 'electronics', thumb = 'prop_phone_cs_frank.png' },
    { name = 'Radio', model = 'prop_radio_01', cat = 'electronics', thumb = 'prop_radio_01.png' },
    { name = 'Camera', model = 'prop_cctv_cam_01a', cat = 'electronics', thumb = 'prop_cctv_cam_01a.png' },
    { name = 'Camera 02', model = 'prop_cctv_cam_04a', cat = 'electronics', thumb = 'prop_cctv_cam_04a.png' },

    -- ---------------- Ev / Yatak Odası / Banyo ----------------
    { name = 'Bed 01', model = 'prop_bed_01', cat = 'home', thumb = 'prop_bed_01.png' },
    { name = 'Bed 02', model = 'prop_bed_02', cat = 'home', thumb = 'prop_bed_02.png' },
    { name = 'Bed 03', model = 'prop_bed_03', cat = 'home', thumb = 'prop_bed_03.png' },
    { name = 'Bed 04', model = 'prop_bed_04', cat = 'home', thumb = 'prop_bed_04.png' },
    { name = 'Wardrobe 01', model = 'p_cs_locker_01', cat = 'home', thumb = 'p_cs_locker_01.png' },
    { name = 'Wardrobe 02', model = 'prop_ld_int_safe_01', cat = 'home', thumb = 'prop_ld_int_safe_01.png' },
    { name = 'Drawer 01', model = 'prop_devin_box_closed', cat = 'home', thumb = 'prop_devin_box_closed.png' },
    { name = 'Drawer 02', model = 'v_res_d_dressingtable', cat = 'home', thumb = 'v_res_d_dressingtable.png' },
    { name = 'Nightstand 01', model = 'v_res_mdbedtable', cat = 'home', thumb = 'v_res_mdbedtable.png' },
    { name = 'Nightstand 02', model = 'v_res_tre_sideboard', cat = 'home', thumb = 'v_res_tre_sideboard.png' },
    { name = 'Laundry Basket', model = 'prop_ld_laundry_basket', cat = 'home', thumb = 'prop_ld_laundry_basket.png' },
    { name = 'Toilet 01', model = 'prop_ld_toilet_01', cat = 'home', thumb = 'prop_ld_toilet_01.png' },
    { name = 'Toilet 02', model = 'prop_toilet_01', cat = 'home', thumb = 'prop_toilet_01.png' },
    { name = 'Sink Bathroom 01', model = 'prop_sink_04', cat = 'home', thumb = 'prop_sink_04.png' },
    { name = 'Sink Bathroom 02', model = 'prop_sink_05', cat = 'home', thumb = 'prop_sink_05.png' },
    { name = 'Bath 01', model = 'prop_bath_01', cat = 'home', thumb = 'prop_bath_01.png' },
    { name = 'Shower 01', model = 'prop_shower_rack_01', cat = 'home', thumb = 'prop_shower_rack_01.png' },
    { name = 'Towel Rail', model = 'prop_towel_rail_01', cat = 'home', thumb = 'prop_towel_rail_01.png' },
    { name = 'Towel Set', model = 'prop_towel_01', cat = 'home', thumb = 'prop_towel_01.png' },
    { name = 'Hair Dryer', model = 'prop_cs_hairdryer', cat = 'home', thumb = 'prop_cs_hairdryer.png' },
    { name = 'Iron Board', model = 'prop_iron_01', cat = 'home', thumb = 'prop_iron_01.png' },
    { name = 'Iron', model = 'prop_iron_03', cat = 'home', thumb = 'prop_iron_03.png' },
    { name = 'Laundry Machine', model = 'prop_washer_01', cat = 'home', thumb = 'prop_washer_01.png' },
    { name = 'Dryer', model = 'prop_washer_02', cat = 'home', thumb = 'prop_washer_02.png' },

    -- ---------------- Ofis / İş Yeri ----------------
    { name = 'Desk Office 01', model = 'prop_office_desk_01', cat = 'office', thumb = 'prop_office_desk_01.png' },
    { name = 'Desk Office 02', model = 'prop_office_desk_02', cat = 'office', thumb = 'prop_office_desk_02.png' },
    { name = 'Chair Office 01', model = 'prop_off_chair_01', cat = 'office', thumb = 'prop_off_chair_01.png' },
    { name = 'Chair Office 02', model = 'prop_off_chair_03', cat = 'office', thumb = 'prop_off_chair_03.png' },
    { name = 'Chair Office 03', model = 'prop_off_chair_04', cat = 'office', thumb = 'prop_off_chair_04.png' },
    { name = 'Chair Office 04', model = 'prop_off_chair_04_s', cat = 'office', thumb = 'prop_off_chair_04_s.png' },
    { name = 'Cabinet 01', model = 'prop_fib_3b_bench', cat = 'office', thumb = 'prop_fib_3b_bench.png' },
    { name = 'Cabinet 02', model = 'prop_fib_cabinet_01', cat = 'office', thumb = 'prop_fib_cabinet_01.png' },
    { name = 'Cabinet 03', model = 'prop_fib_cabinet_02', cat = 'office', thumb = 'prop_fib_cabinet_02.png' },
    { name = 'Filing Cabinet 01', model = 'prop_fbibombfile', cat = 'office', thumb = 'prop_fbibombfile.png' },
    { name = 'Whiteboard', model = 'prop_whiteboard', cat = 'office', thumb = 'prop_whiteboard.png' },
    { name = 'Projector', model = 'prop_projector_overlay', cat = 'office', thumb = 'prop_projector_overlay.png' },
    { name = 'Desk Fan', model = 'prop_fan_01', cat = 'office', thumb = 'prop_fan_01.png' },
    { name = 'Wall Fan', model = 'prop_fan_palm_01a', cat = 'office', thumb = 'prop_fan_palm_01a.png' },
    { name = 'Safe 01', model = 'prop_ld_int_safe_01', cat = 'office', thumb = 'prop_ld_int_safe_01.png' },
    { name = 'Safe 02', model = 'p_v_43_safe_s', cat = 'office', thumb = 'p_v_43_safe_s.png' },
    { name = 'Briefcase', model = 'prop_ld_case_01', cat = 'office', thumb = 'prop_ld_case_01.png' },
    { name = 'Clipboard', model = 'p_amb_clipboard_01', cat = 'office', thumb = 'p_amb_clipboard_01.png' },
    { name = 'Paper Box', model = 'prop_boxpaper_01a', cat = 'office', thumb = 'prop_boxpaper_01a.png' },
    { name = 'Paper Box 02', model = 'prop_boxpaper_02a', cat = 'office', thumb = 'prop_boxpaper_02a.png' },
    { name = 'Paper Box 03', model = 'prop_boxpaper_03a', cat = 'office', thumb = 'prop_boxpaper_03a.png' },

    -- ---------------- Fight Club / Spor ----------------
    { name = 'Boxing Bag 01', model = 'prop_boxing_bag_01', cat = 'gym', thumb = 'prop_boxing_bag_01.png' },
    { name = 'Boxing Bag 02', model = 'prop_boxing_bag_01b', cat = 'gym', thumb = 'prop_boxing_bag_01b.png' },
    { name = 'Weight Rack 01', model = 'prop_weight_rack_01', cat = 'gym', thumb = 'prop_weight_rack_01.png' },
    { name = 'Weight Bench', model = 'prop_weight_bench_02', cat = 'gym', thumb = 'prop_weight_bench_02.png' },
    { name = 'Punching Bench', model = 'prop_bench_press_01', cat = 'gym', thumb = 'prop_bench_press_01.png' },
    { name = 'Gym Bench 01', model = 'prop_muscle_bench_03', cat = 'gym', thumb = 'prop_muscle_bench_03.png' },
    { name = 'Gym Bench 02', model = 'prop_muscle_bench_04', cat = 'gym', thumb = 'prop_muscle_bench_04.png' },
    { name = 'Gym Bench 03', model = 'prop_muscle_bench_05', cat = 'gym', thumb = 'prop_muscle_bench_05.png' },
    { name = 'Dumbbell Set', model = 'prop_weight_squat', cat = 'gym', thumb = 'prop_weight_squat.png' },
    { name = 'Barbell', model = 'prop_barbell_01', cat = 'gym', thumb = 'prop_barbell_01.png' },
    { name = 'Gym Bike', model = 'prop_exercisebike', cat = 'gym', thumb = 'prop_exercisebike.png' },
    { name = 'Treadmill', model = 'prop_treadmill_01', cat = 'gym', thumb = 'prop_treadmill_01.png' },
    { name = 'Yoga Mat 01', model = 'prop_yoga_mat_01', cat = 'gym', thumb = 'prop_yoga_mat_01.png' },
    { name = 'Yoga Mat 02', model = 'prop_yoga_mat_02', cat = 'gym', thumb = 'prop_yoga_mat_02.png' },
    { name = 'Yoga Mat 03', model = 'prop_yoga_mat_03', cat = 'gym', thumb = 'prop_yoga_mat_03.png' },
    { name = 'Locker 01', model = 'p_cs_locker_01', cat = 'gym', thumb = 'p_cs_locker_01.png' },
    { name = 'Locker 02', model = 'prop_ld_int_safe_01', cat = 'gym', thumb = 'prop_ld_int_safe_01.png' },
    { name = 'Bench Crowd 01', model = 'prop_bench_01a', cat = 'gym', thumb = 'prop_bench_01a.png' },
    { name = 'Bench Crowd 02', model = 'prop_bench_03', cat = 'gym', thumb = 'prop_bench_03.png' },
    { name = 'Ring Bell Table', model = 'prop_table_03b', cat = 'gym', thumb = 'prop_table_03b.png' },
    { name = 'Industrial Light Gym', model = 'prop_ind_light_02a', cat = 'gym', thumb = 'prop_ind_light_02a.png' },

    -- ---------------- Depo / Industrial / Tamirhane ----------------
    { name = 'Crate 01', model = 'prop_box_wood01a', cat = 'warehouse', thumb = 'prop_box_wood01a.png' },
    { name = 'Crate 02', model = 'prop_box_wood02a', cat = 'warehouse', thumb = 'prop_box_wood02a.png' },
    { name = 'Crate 03', model = 'prop_box_wood03a', cat = 'warehouse', thumb = 'prop_box_wood03a.png' },
    { name = 'Crate 04', model = 'prop_box_wood04a', cat = 'warehouse', thumb = 'prop_box_wood04a.png' },
    { name = 'Crate 05', model = 'prop_box_wood05a', cat = 'warehouse', thumb = 'prop_box_wood05a.png' },
    { name = 'Crate 06', model = 'prop_box_wood06a', cat = 'warehouse', thumb = 'prop_box_wood06a.png' },
    { name = 'Crate 07', model = 'prop_box_wood07a', cat = 'warehouse', thumb = 'prop_box_wood07a.png' },
    { name = 'Pallet 01', model = 'prop_pallet_01a', cat = 'warehouse', thumb = 'prop_pallet_01a.png' },
    { name = 'Pallet 02', model = 'prop_pallet_02a', cat = 'warehouse', thumb = 'prop_pallet_02a.png' },
    { name = 'Pallet 03', model = 'prop_pallet_03a', cat = 'warehouse', thumb = 'prop_pallet_03a.png' },
    { name = 'Pallet 04', model = 'prop_pallet_04a', cat = 'warehouse', thumb = 'prop_pallet_04a.png' },
    { name = 'Barrel 01', model = 'prop_barrel_01a', cat = 'warehouse', thumb = 'prop_barrel_01a.png' },
    { name = 'Barrel 02', model = 'prop_barrel_02a', cat = 'warehouse', thumb = 'prop_barrel_02a.png' },
    { name = 'Barrel 03', model = 'prop_barrel_03a', cat = 'warehouse', thumb = 'prop_barrel_03a.png' },
    { name = 'Gas Canister 01', model = 'prop_gascyl_01a', cat = 'warehouse', thumb = 'prop_gascyl_01a.png' },
    { name = 'Gas Canister 02', model = 'prop_gascyl_02a', cat = 'warehouse', thumb = 'prop_gascyl_02a.png' },
    { name = 'Gas Canister 03', model = 'prop_gascyl_03a', cat = 'warehouse', thumb = 'prop_gascyl_03a.png' },
    { name = 'Gas Canister 04', model = 'prop_gascyl_04a', cat = 'warehouse', thumb = 'prop_gascyl_04a.png' },
    { name = 'Tool Chest 01', model = 'prop_toolchest_01', cat = 'warehouse', thumb = 'prop_toolchest_01.png' },
    { name = 'Tool Chest 02', model = 'prop_toolchest_02', cat = 'warehouse', thumb = 'prop_toolchest_02.png' },
    { name = 'Tool Box 01', model = 'prop_tool_box_04', cat = 'warehouse', thumb = 'prop_tool_box_04.png' },
    { name = 'Tool Box 02', model = 'prop_tool_box_05', cat = 'warehouse', thumb = 'prop_tool_box_05.png' },
    { name = 'Work Light 01', model = 'prop_worklight_01a', cat = 'warehouse', thumb = 'prop_worklight_01a.png' },
    { name = 'Work Light 02', model = 'prop_worklight_02a', cat = 'warehouse', thumb = 'prop_worklight_02a.png' },
    { name = 'Work Light 03', model = 'prop_worklight_03a', cat = 'warehouse', thumb = 'prop_worklight_03a.png' },
    { name = 'Work Light 04', model = 'prop_worklight_04a', cat = 'warehouse', thumb = 'prop_worklight_04a.png' },
    { name = 'Generator 01', model = 'prop_generator_01a', cat = 'warehouse', thumb = 'prop_generator_01a.png' },
    { name = 'Generator 02', model = 'prop_generator_02a', cat = 'warehouse', thumb = 'prop_generator_02a.png' },
    { name = 'Air Con 01', model = 'prop_aircon_m_02', cat = 'warehouse', thumb = 'prop_aircon_m_02.png' },
    { name = 'Air Con 02', model = 'prop_aircon_l_03', cat = 'warehouse', thumb = 'prop_aircon_l_03.png' },
    { name = 'Compressor', model = 'prop_compressor_03', cat = 'warehouse', thumb = 'prop_compressor_03.png' },
    { name = 'Engine Hoist', model = 'prop_engine_hoist', cat = 'warehouse', thumb = 'prop_engine_hoist.png' },
    { name = 'Hydraulic Lift', model = 'prop_carjack', cat = 'warehouse', thumb = 'prop_carjack.png' },
    { name = 'Mechanic Creeper', model = 'prop_cs_cardbox_01', cat = 'warehouse', thumb = 'prop_cs_cardbox_01.png' },
    { name = 'Forklift', model = 'prop_forklift_01', cat = 'warehouse', thumb = 'prop_forklift_01.png' },
    { name = 'Pump 01', model = 'prop_waterpump', cat = 'warehouse', thumb = 'prop_waterpump.png' },
    { name = 'Pump 02', model = 'prop_pump_1a', cat = 'warehouse', thumb = 'prop_pump_1a.png' },
    { name = 'Welding Tank', model = 'prop_welding_mask_01', cat = 'warehouse', thumb = 'prop_welding_mask_01.png' },
    { name = 'Scrap Metal 01', model = 'prop_rub_scrap_02', cat = 'warehouse', thumb = 'prop_rub_scrap_02.png' },
    { name = 'Scrap Metal 02', model = 'prop_rub_scrap_03', cat = 'warehouse', thumb = 'prop_rub_scrap_03.png' },
    { name = 'Scrap Metal 03', model = 'prop_rub_scrap_04', cat = 'warehouse', thumb = 'prop_rub_scrap_04.png' },

    -- ---------------- Dış Mekan / Sokak / Kulüp ----------------
    { name = 'Street Bench 01', model = 'prop_bench_01a', cat = 'outdoor', thumb = 'prop_bench_01a.png' },
    { name = 'Street Bench 02', model = 'prop_bench_01b', cat = 'outdoor', thumb = 'prop_bench_01b.png' },
    { name = 'Street Bench 03', model = 'prop_bench_01c', cat = 'outdoor', thumb = 'prop_bench_01c.png' },
    { name = 'Street Bench 04', model = 'prop_bench_02', cat = 'outdoor', thumb = 'prop_bench_02.png' },
    { name = 'Street Bench 05', model = 'prop_bench_03', cat = 'outdoor', thumb = 'prop_bench_03.png' },
    { name = 'Street Bench 06', model = 'prop_bench_04', cat = 'outdoor', thumb = 'prop_bench_04.png' },
    { name = 'Parasol 01', model = 'prop_parasol_01', cat = 'outdoor', thumb = 'prop_parasol_01.png' },
    { name = 'Parasol 02', model = 'prop_parasol_02', cat = 'outdoor', thumb = 'prop_parasol_02.png' },
    { name = 'Parasol 03', model = 'prop_parasol_03', cat = 'outdoor', thumb = 'prop_parasol_03.png' },
    { name = 'Patio Heater', model = 'prop_patio_heater_01', cat = 'outdoor', thumb = 'prop_patio_heater_01.png' },
    { name = 'Ash Bin', model = 'prop_bin_07a', cat = 'outdoor', thumb = 'prop_bin_07a.png' },
    { name = 'Wheelie Bin 01', model = 'prop_bin_08a', cat = 'outdoor', thumb = 'prop_bin_08a.png' },
    { name = 'Wheelie Bin 02', model = 'prop_bin_10a', cat = 'outdoor', thumb = 'prop_bin_10a.png' },
    { name = 'Dumpster 01', model = 'prop_dumpster_01a', cat = 'outdoor', thumb = 'prop_dumpster_01a.png' },
    { name = 'Dumpster 02', model = 'prop_dumpster_02a', cat = 'outdoor', thumb = 'prop_dumpster_02a.png' },
    { name = 'Dumpster 03', model = 'prop_dumpster_02b', cat = 'outdoor', thumb = 'prop_dumpster_02b.png' },
    { name = 'Dumpster 04', model = 'prop_dumpster_3a', cat = 'outdoor', thumb = 'prop_dumpster_3a.png' },
    { name = 'Cone 01', model = 'prop_roadcone01a', cat = 'outdoor', thumb = 'prop_roadcone01a.png' },
    { name = 'Cone 02', model = 'prop_roadcone02a', cat = 'outdoor', thumb = 'prop_roadcone02a.png' },
    { name = 'Cone 03', model = 'prop_mp_cone_01', cat = 'outdoor', thumb = 'prop_mp_cone_01.png' },
    { name = 'Traffic Barrier', model = 'prop_mp_barrier_01', cat = 'outdoor', thumb = 'prop_mp_barrier_01.png' },
    { name = 'Arrow Barrier', model = 'prop_mp_arrow_barrier_01', cat = 'outdoor', thumb = 'prop_mp_arrow_barrier_01.png' },
    { name = 'Queue Barrier 01', model = 'prop_barrier_wat_03a', cat = 'outdoor', thumb = 'prop_barrier_wat_03a.png' },
    { name = 'Queue Barrier 02', model = 'prop_barier_conc_05c', cat = 'outdoor', thumb = 'prop_barier_conc_05c.png' },
    { name = 'Speaker Stack 01', model = 'prop_speaker_06', cat = 'outdoor', thumb = 'prop_speaker_06.png' },
    { name = 'Speaker Stack 02', model = 'prop_speaker_07', cat = 'outdoor', thumb = 'prop_speaker_07.png' },
    { name = 'Speaker Stack 03', model = 'prop_speaker_08', cat = 'outdoor', thumb = 'prop_speaker_08.png' },
    { name = 'Speaker Stack 04', model = 'prop_clubset', cat = 'outdoor', thumb = 'prop_clubset.png' },
    { name = 'Disco Ball', model = 'prop_ld_greenscreen_01', cat = 'outdoor', thumb = 'prop_ld_greenscreen_01.png' },
    { name = 'Club Light 01', model = 'prop_wall_light_05a', cat = 'outdoor', thumb = 'prop_wall_light_05a.png' },
    { name = 'Club Light 02', model = 'prop_wall_light_05c', cat = 'outdoor', thumb = 'prop_wall_light_05c.png' },
    { name = 'Club Light 03', model = 'prop_wall_light_05a', cat = 'outdoor', thumb = 'prop_wall_light_05a.png' },
    { name = 'Rope Barrier 01', model = 'p_gold_hoops', cat = 'outdoor', thumb = 'p_gold_hoops.png' },
    { name = 'Stage Speaker', model = 'prop_speaker_05', cat = 'outdoor', thumb = 'prop_speaker_05.png' },
}

-- index by model (light entries win over duplicates so the glow still works)
Config.CatalogByModel = {}
for _, it in ipairs(Config.Catalog) do
    local prev = Config.CatalogByModel[it.model]
    if not prev or (it.light and not prev.light) then
        Config.CatalogByModel[it.model] = it
    end
end

